.editorconfig
.github/CODEOWNERS
.github/workflows/pull-request-main.yml
.gitignore
.tool-versions
go.mod
go.sum
placeholder_test.go

Setting up some basic checks before i start adding code here
- codeowners
- lint and test workflows
- push tag workflow
- gitignore & editor config
JIRA: https://smartcontract-it.atlassian.net/browse/CLD-128

[CLD-128]: chore: setup lint and test

---

.github/workflows/push-tag-release.yml
.goreleaser.yml
package.json
pnpm-lock.yaml

- Add push tag workflow
- setup goreleaser config
- npm commands to running changeset release
JIRA: https://smartcontract-it.atlassian.net/browse/CLD-127

[CLD-127]: ci: setup go releaser

---

.changeset/funny-countries-notice.md
.github/workflows/pull-request-main.yml
datastore/transform.go
datastore/transform_test.go

This PR adds `datastore` utility functions for converting between domain-specific types and the DefaultMetadata type.
* [`datastore/transform.go`](https://github.com/smartcontractkit/chainlink-deployments-framework/blob/c4a09a68da380674a03b8e56c74d53d91c2ddcfc/datastore/transform.go): Added `ToDefault` and `FromDefault` utility functions for converting between domain-specific metadata types and `DefaultMetadata` types

feat: adds datastore conversion utilities

---

.changeset/yummy-clouds-argue.md
datastore/filters.go
datastore/filters_test.go

Add an address filter. Usecase I have for this is to quickly check if the contract address I have is the expected one
```
records := store.Filter(
AddressRefByAddress("0x1234"),
AddressRefByChainSelector(1),
AddressRefByType(ContractType("MyType")),
AddressRefByVersion("0.5.0"),
)
if len(records) == 1 .... 
```
It probably should have it's own dedicated function in the datastore to get a single expected record.

Data store/add address filter

---

.changeset/three-melons-stand.md
datastore/address_ref.go
datastore/label_set.go
datastore/label_set_test.go

This commit improves the JSON serialization of the LabelSet struct by changing the way labels are represented in JSON. Instead of using a map with string keys and string values, the labels are now represented as an array of strings. This change simplifies the JSON structure and makes it easier to work with labels in a more intuitive way.

feature: serialize JSON LabelSet as array of strings

---

deployment/multiclient.go

Remove noisy log which make it harder to read through.

chore(multiclient):remove noisy debug log

---

.changeset/major-eyes-wish.md
deployment/ocr_secrets.go

Copy ocr secrets helpers from chainlink repo to here. This is a lift and shift, nothing was changed
[JIRA: https://smartcontract-it.atlassian.net/browse/CLD-130](https://smartcontract-it.atlassian.net/browse/CLD-153)

feat(deployment):migrate in ocr secrets

---

.changeset/rotten-plums-wish.md
deployment/environment.go
go.mod
go.sum

Copy ocr secrets helpers from chainlink repo to here. This is a lift and shift, nothing was changed
[JIRA: https://smartcontract-it.atlassian.net/browse/CLD-129](https://smartcontract-it.atlassian.net/browse/CLD-129)

feat(environment):migrate offchain client interface

---

.changeset/breezy-maps-tell.md
deployment/multiclient.go

This PR extends the MultiClient implementation with additional method overrides to help surface errors originating from the underlying ethclient. The goal is to improve visibility into the flakiness observed when running changesets through CI and GAP, and to help identify the specific call causing the issue. 
The additional overrides cover all method calls that can be invoked as part of a `transact` call, as seen [here](https://github.com/ethereum/go-ethereum/blob/612c9e0f4ae483f180ef96ace86effec6dc9bb0e/accounts/abi/bind/base.go#L390).

feat: adds debug logs to ethclient direct calls

---

.changeset/tidy-doors-film.md
deployment/multiclient.go
deployment/multiclient_test.go

- better logging with trace id, in logs where there are multiple calls with the same chain name, we are unable to tell if the retry attempt logs are from the same call or different, having a traceID will make this more obvious and help with debugging.
- expose dial attempts and delay as external config so it can be configured.
JIRA: https://smartcontract-it.atlassian.net/browse/CLD-210

[CLD-210]: feat(mutliclient): better log & expose dial config

---

.changeset/tangy-plums-draw.md
operations/execute.go
operations/execute_test.go
operations/report.go
operations/report_test.go

BREAKING CHANGE: The retry logic for operations is now opt-in. To enable the retry, the caller must now provide the `WithRetry` option to the `ExecuteOperation`. This change is intended to provide greater control over the retry behavior and to avoid unintended retries in certain scenarios.

feat: change operations retry logic to be opt-in

---

deployment/multiclient.go

We see warnings for retry attempts but we never confirm we were successful after them. It's to make better ux for the users.

logs(multiclient):add retry success log

---

.changeset/clean-carrots-hide.md
deployment/multiclient.go

This PR replaces temporary debug-wrapped calls in MultiClient with proper retry logic to improve resilience and reduce the impact of transient failures. Recent improvements (debug logs and refined retry logic) have stabilized MultiClient. The debug wrappers are no longer needed and can be replaced with the same retry logic that already wraps other calls.

feat(multiclient): wraps debug calls with retry logic

---

.changeset/small-towns-unite.md
deployment/address_book.go
deployment/address_book_test.go

During the previous [lint fixes here](https://github.com/smartcontractkit/chainlink-deployments-framework/pull/71/files), the strings in the error message were reversed, we should maintain the same order. This is causing some tests to fail in Chainlink.
Added unit tests for it.

fix(addressbook): fix error message

---

.changeset/weak-llamas-smash.md
deployment/multiclient.go
deployment/multiclient_test.go

- Improve logging to be more structured
- Added number of retries on success message for more context 
- Only log success when retry is attempted to avoid too much noise as we have a lot of RPC x Chains
Currently, the success log is [quite noisy](https://chainlink-core.slack.com/files/U077HN1LJLV/F08SU9H3EQ0/migration.logs?origin_channel=Vall_threads) because it is logging on every success call. This will remove the noisiness.

fix(multiclient): enhance logging

---

.changeset/fancy-cows-sniff.md
deployment/solana_chain.go

These constants are product specific and should not be coupled with the DeployProgram function. This refactors the method to accept programBytes instead and I will be moving the program bytes map back into Chainlink repo
JIRA: https://smartcontract-it.atlassian.net/browse/CLD-208

[CLD-208]: fix(chain): refactor solana DeployProgram to accept ProgramBytes

---

.changeset/itchy-dragons-shout.md
.github/workflows/pull-request-main.yml
operations/execute_test.go
operations/report.go

CCIP team has raised that they want to start using Operations API and they have a use case where they wan to deploy multiple contracts in parallel (multiple go routine calling executeSequence), currently Operations API is not thread safe due to the reporter.
- update MemoryReporter and RecentReporter to be thread safe
JIRA: https://smartcontract-it.atlassian.net/browse/CLD-272

[CLD-272]: feat(operations): enable concurrency support

---

.changeset/cruel-keys-bathe.md
deployment/changeset.go
go.mod
go.sum

Removes the `Proposals` field from the `ChangesetOutput` struct. Use the `MCMSTimelockProposals` struct instead which provides an implementation based on the upgraded `mcms` library
BREAKING CHANGE:  This field was previously marked as deprecated and has now been removed.

refactor: remove proposals field from ChangesetOutput

---

.github/workflows/schedule-main.yml

This pull request updates the SonarQube workflow in `.github/workflows/schedule-main.yml` to improve its configuration and functionality. The changes include removing a conditional check and adding a new parameter to the SonarQube step.
Updates to SonarQube workflow:
* Removed the conditional `if: github.event_name == 'pull_request'` from the SonarQube job, allowing it to run regardless of the event type.
* Added a new `include-lint: true` parameter to the SonarQube step to include linting results in the scan.

fix(sonar):include lint in schedule main

---

.changeset/angry-trains-end.md
chain/blockchain.go
chain/blockchain_test.go

Adds two methods `Exists` and `ExistsN` to the Blockchain struct to check if a chain exists in the database.
`Exists` checks the existence of a single selector to return true. `ExistsN` checks the existence of multiple selectors, all of which must exist for the method to return true.

feat: add methods to test for the existence of a chain

---

.changeset/fuzzy-maps-rhyme.md
chain/blockchain.go
chain/blockchain_test.go

blockchain getter functions return value for error is always nil, so it is not used at all, lets get rid of it.

fix(chains): remove unused error

---

.changeset/ninety-bottles-ring.md
chain/aptos/aptos_chain.go
chain/blockchain_test.go
chain/evm/evm_chain.go
chain/internal/common/chain_metadata_test.go
chain/solana/solana_chain.go
chain/sui/sui_chain.go
chain/sui/sui_chain_test.go
chain/ton/ton_chain.go
chain/ton/ton_chain_test.go

The original intention was not to compose ChainMetadata and just use it directly by explicitly implementing the ChainMetadata interface and calling ChainMetadatato avoid breaking existing compatibility with EVM, SOL and APTOS and also the clunky initiation code.
However this introduces some duplication across all chains.
So the compromise is to still have the duplication in the existing chains but for new chains, they will compose the ChainMetadata and to avoid referencing another package for the ChainMetadata (clunky), the type alias is introduced.

fix: Update SUI & Ton to compose ChainMetadata

---

.changeset/early-forks-dress.md
datastore/address_ref_key.go
datastore/address_ref_key_test.go
datastore/contract_metadata_key.go
datastore/contract_metadata_key_test.go

This pull request introduces enhancements to the `datastore` package by implementing the `fmt.Stringer` interface for key types and adding corresponding unit tests. These changes improve the readability and debugging of key representations.
* [`datastore/address_ref_key.go`](diffhunk://#diff-a8f748a3f09f8874d72a162c5254eff51b1666cedf9059510125a0c4daf5f2e3R4-R13): Added the `fmt.Stringer` interface to the `AddressRefKey` type, including a new `String` method that provides a formatted string representation of the key. [[1]](diffhunk://#diff-a8f748a3f09f8874d72a162c5254eff51b1666cedf9059510125a0c4daf5f2e3R4-R13) [[2]](diffhunk://#diff-a8f748a3f09f8874d72a162c5254eff51b1666cedf9059510125a0c4daf5f2e3R60-R69)
* [`datastore/contract_metadata_key.go`](diffhunk://#diff-d9574b8aedc2795d729a5c1d72ecf …

feat(datastore): Implement Stringer for ContractMetadata and AddressRef Keys

---

.changeset/gold-eels-exist.md
chain/blockchain.go
chain/blockchain_test.go

- Use map instead of slice for faster lookup
- WithFamily now supports more than 1 family, eg `ListChainSelectors(WithFamily("evm"), WithFamily("aptos")`

fix(chain): ListChainSelectors filter with multiple families

---

.changeset/sour-mangos-roll.md
operations/execute.go
operations/execute_test.go

The number of attempts and error can be useful to allow user to decide for example gas number for the next attempt.

feat(operations): add useful params to inputhook

---

.changeset/tidy-donuts-learn.md
deployment/environment.go

This function was not used, and it was removed to clean up the codebase. Users can write their own function to retrieve deployer keys if needed.

feat: remove unused function `AllDeployerKeys`

---

.changeset/floppy-nails-repeat.md
chain/blockchain.go
chain/blockchain_test.go
operations/validation.go

For getters like EVMChains, if the underlying struct is a pointer, the type assertion will fail because it only checks if it is a non pointer. This commits update it to handle the pointer type.

fix(chain): handle pointer chain type for getters

---

.changeset/silver-rules-add.md
datastore/abstract.go
datastore/clone.go
datastore/clone_test.go
datastore/contract_metadata.go
datastore/contract_metadata_test.go
datastore/env_metadata.go
datastore/env_metadata_test.go
datastore/filters.go
datastore/memory_contract_metadata_store.go
datastore/memory_datastore.go
datastore/memory_env_metadata_store.go
datastore/transform.go
datastore/transform_test.go

This PR simplifies `datastore` custom metadata handling by removing the need for users to implement Clone.
We now provide a built-in generic Clone implementation using Go’s JSON serialization, based on the assumption that all metadata types are JSON-serializable, which has always been the case.

feat(datastore): removes Clone requirement for custom metadata types

---

.changeset/large-baths-know.md
chain/solana/provider/rpc_provider.go
chain/solana/provider/rpc_provider_test.go
chain/solana/provider/rpcclient/client.go
chain/solana/provider/rpcclient/client_test.go
chain/solana/provider/rpcclient/tx_modifier.go
chain/solana/solana_chain.go

This PR introduces a new Solana RPC client wrapper (`chain/solana/provider/rpcclient`) to provide enhanced transaction handling, including support for retries, transaction modifiers, and simplified confirmation flows.
This RPC Client wrapper code is a modifed version of the the one found in `chainlink-ccip` utils. This allows us to avoid importing the entire `chainlink-ccip` package.
https://github.com/smartcontractkit/chainlink-ccip/blob/e52d53e1d7f00babee52e4dc462d9f69fbf1466b/chains/solana/utils/common/transactions.go

feat: provide a SendAndConfirmFunction on the Solana Chain

---

.changeset/cute-pans-cheer.md
operations/execute.go
operations/execute_test.go
operations/report.go
operations/report_test.go

There is a scenario discovered when an operation with same input has to be run multiple times, eg when deploying the same MCMS contract multiple times so it can be associated with different roles.
This commit introduces `ExecutionOperationN`, it will execute the provided operation N times.
For idempotency behaviour, we went to ensure on reruns, the `ExecutionOperationN` will return the successful prior results in the same order in the slice. That is why we need to remember the order.
Usage
```go
// execute 3 times
linkDeployReports, err := operations.ExecuteOperationN(
b, DeployLinkOp, deps, operations.EmptyInput{},
"deploy-multiple-link-contract", 3,
operations.WithRetry[operations.EmptyInput, EthereumDeps](),
)
```
Report
```
{
"id": "15ac8420-0b59-4293-a188-948ad43643da",
"definition": …
```

[CLD-302]: feat(operations): introduce ExecutionOperationN

---

.changeset/cold-steaks-matter.md
chain/aptos/provider/ctf_provider.go
chain/aptos/provider/ctf_provider_test.go
chain/aptos/provider/rpc_provider.go
chain/aptos/provider/rpc_provider_test.go
chain/provider.go
chain/solana/provider/ctf_provider.go
chain/solana/provider/ctf_provider_test.go
chain/solana/provider/rpc_provider.go
chain/solana/provider/rpc_provider_test.go

The context parameter is now required for the `Initialize` method in the `chain.Provider` interface. This change is made to ensure that all providers can handle context-specific operations such as setting up clients.
BREAKING CHANGE: This change requires all calls to Initialize to pass a Context parameter. This is a breaking change as it modifies the signature of the `Initialize` method in the `chain.Provider` interface.

feat: The Initialize method on chain.Provider now requires a Context

---

CHANGELOG.md

Due to a [ci failure](https://github.com/smartcontractkit/chainlink-deployments-framework/actions/runs/15549473823), version 0.11.0 never existed, the changes are released in 0.12.0, updating the CHANGELOG.md accordingly

docs: remove 0.11.0 in changelog

---

.changeset/every-steaks-matter.md
go.mod
go.sum

This change fixes an issue with imports on the `chainlink` repo where the existing declared version was not associated with a ccip-solana release

fix: update chainlink-solana dep to match the version in chainlink

---

.changeset/thin-carpets-punch.md
chain/solana/provider/rpc_provider.go
chain/solana/provider/rpc_provider_test.go

This commit makes the `wsurl` field in the Solana Provider optional, as existing implementations do not require a WebSocket URL.

fix: make the wsurl for Solana Provider optional

---

.changeset/afraid-chefs-eat.md
chain/evm/provider/sim_client.go
chain/evm/provider/sim_client_test.go

This addds a `Backend` method to the `SimClient`, which returns the underlying backend. This is useful when you want to provide the underlying backend to other components that require the same backend.

feat: add a method to return the underlying backend of a SimClient

---

chain/evm/provider/zksync_ctf_provider_test.go

Super flaky even failing with the 10 retries that we added.

tests: disable zksync intialize test

---

.changeset/ready-coins-go.md
.github/workflows/pull-request-main.yml
.github/workflows/schedule-main.yml
chain/ton/provider/ctf_provider.go
chain/ton/provider/ctf_provider_test.go

Create new CTF provider for ton chain. Migrated the code from Chainlink [here](https://github.com/smartcontractkit/chainlink/blob/1d22b7e8f9f52d4e1725bffaf9eb49d1132152d2/deployment/environment/memory/ton_chains.go#L71-L71), adjusted it to fit the design and added some testing.
JIRA: https://smartcontract-it.atlassian.net/browse/CLD-424

feat(ton): new ctf provider

---

chain/aptos/provider/ctf_provider.go
chain/evm/provider/zksync_ctf_provider.go
chain/evm/provider/zksync_ctf_provider_test.go
chain/solana/provider/ctf_provider.go
chain/solana/provider/rpcclient/client_test.go

Earlier some test that starts docker container were skipped due to flakiness. I have been running them again the CI many times, and it doesnt seem to be flaky anymore, I will enable the tests again and monitor them.
Also updated the string for chain type to use the enum from CTF
JIRA: https://smartcontract-it.atlassian.net/browse/CLD-429

[CLD-429]: test: enable skipped test and improve readiness check

---

.changeset/salty-books-kick.md
go.mod
go.sum
offchain/jd/client.go
offchain/jd/client_test.go
offchain/jd/doc.go
offchain/jd/interceptor.go
offchain/jd/interceptor_test.go
offchain/jd/provider/client_provider.go
offchain/jd/provider/client_provider_test.go
offchain/offchain.go
offchain/provider.go

Migrated the JD client and introduced a offchain provider for JD.
Note this JD client is missing the DON capability compared to the JD client in Chainlink repo. This is because DON capability involves bringing over a huge amount of code (including generated code) from the Chainlink repo which is currently not used in CLD.
JIRA: https://smartcontract-it.atlassian.net/browse/CLD-480

[CLD-480]: feat: added JD client and provider

---

.changeset/cool-pans-float.md
go.mod
go.sum

Removing the replace line for gogo/protobuf, it is forcing Chainlink repo to perform the same replace when importing CLDF. This was added as part of the TRON chain implementation
This commit remove the replace, and uses the gogo/protobuf v1.3.2 instead

fix: remove gogo/protobuf, use v1.3.2

---

.changeset/better-singers-nail.md
engine/cld/nodes/nodes.go
engine/cld/nodes/nodes_test.go

Migrates nodes logic from cld pkg/migrations/nodes.
https://smartcontract-it.atlassian.net/browse/CLD-475

migration(nodes): from cld to cldf

---

.changeset/cuddly-crabs-serve.md
deployment/environment.go

Should use offchain.Client going forward
- CLD has already been updated
- Chainlink has this [pending PR](https://github.com/smartcontractkit/chainlink/pull/18866)
JIRA: https://smartcontract-it.atlassian.net/browse/CLD-487

[CLD-487]: fix: remove OffchainClient alias

---

.changeset/curly-olives-write.md
chain/ton/provider/ctf_provider.go

The initialize test for TON [started failing today](https://github.com/smartcontractkit/chainlink-deployments-framework/actions/runs/16870505111/job/47784398103?pr=253) even in main branch when it was previously passing, i did some investigation and looks like there was a new "latest" tag image published just recently - https://github.com/neodix42/mylocalton-docker/pkgs/container/mylocalton-docker, this image stops the container from starting up, opted to use `dev` image since that is working.
This unblocks all PRs due to the failing test

test(TON): use dev image for ton CTF provider

---

.changeset/cute-tigers-smell.md
engine/cld/config/network/config.go
engine/cld/config/network/config_test.go

This refactor changes the URL Transform Load Option to accept a simple transform function, and moves the logic of which URLs to transform to the config itself.
This simplifies the caller's API and avoids exposing the internal config structure to the caller.

refactor: refactor network url transformer

---

chain/sui/provider/ctf_provider.go
go.mod
go.sum

Previously sui node always occupy port 9000 on the host because there was no way to customize it. Since then i have made [a change in CTF](https://github.com/smartcontractkit/chainlink-testing-framework/pull/2044) to allow that ability.
JIRA: https://smartcontract-it.atlassian.net/browse/CLD-500

fix(sui): allocate freeport to sui node

---

.changeset/angry-pugs-wish.md
engine/cld/config/network/config.go
engine/cld/config/network/config_test.go

The previous `WithRPCURLTransformer` load option was a single function that transformed both HTTP and WS URLs. This is too general and makes the assumption that the caller wants to transform all the URLs with the same function.
This PR introduces 2 new load options: `WithHTTPURLTransformer` and `WithWSURLTransformer` which are more specific and allow the caller to transform only or both the HTTP or WS URLs, with different functions.

feat: Replace WithRPCURLTransformer with targeted transformers

---

.changeset/free-foxes-melt.md
chain/tron/provider/ctf_provider_test.go
chain/tron/provider/kms_signer.go
chain/tron/provider/kms_signer_test.go
chain/tron/provider/rpc_provider_test.go
chain/tron/provider/signer_generator.go
chain/tron/provider/signer_generator_test.go

- Instead of initializing the kms client on signing, we perform it on construction for early detection of error. Constructor now returns error.
- allow kms client to be injected for testing
- update testing with mock and cleaned up some duplicate test
JIRA: https://smartcontract-it.atlassian.net/browse/CLD-493

[CLD-493]: fix(tron): remove lazy loading for kms & test cleanup

---

.changeset/lemon-knives-unite.md
engine/cld/config/env/config.go
engine/cld/config/env/config_test.go
engine/cld/config/env/testdata/empty.yml

This is a breaking change because it changes the type of the JobDistributorConfig.Auth field from JobDistributorAuth to *JobDistributorAuth.
This is required because JobDistributor Auth details are optional and can be omitted to skip JD loading.

fix: Job Distributor config is optional and should be nil if not set

---

.changeset/witty-houses-post.md
chain/sui/provider/ctf_provider.go

We sometimes use an `arm64` image instead of the default `amd64` for Sui. This change edits the `CTFChainProviderConfig` for Sui CTF provider to allow passing that config into CTF.

Update Sui CTF provider configs to allow specifying image and platform

---

.changeset/crazy-moose-warn.md
engine/cld/domain/domain.go
engine/cld/domain/domain_test.go
engine/cld/domain/envdir_test.go
engine/cld/domain/paths.go

This change adds more paths for the domain config dirs and files so they can be called on the domain struct. This aims to provide a way to access the expected paths for the domain config dirs and files.

feat: add more domain paths for the config dirs and files

---

.changeset/young-colts-chew.md
chain/evm/provider/signer_generator.go
chain/evm/provider/signer_generator_test.go

This pull request introduces support for specifying a gas limit when generating a raw signer in the Chainlink deployments framework. The changes add a flexible options pattern to the signer generator, allowing users to set a custom gas limit if needed. Unit tests have been updated to cover this new functionality.
**New feature: Gas limit support for raw signer generator**
- Added a `GeneratorOptions` struct and options pattern (`GeneratorOption`, `WithGasLimit`) to `signer_generator.go`, enabling configuration of gas limit for raw signers.
- Updated `TransactorFromRaw` to accept options and set the gas limit on the generated transactor if provided. [[1]](diffhunk://#diff-d969a93d4b9bf394c24013f13cd08f330806edf95bd4536a0e3b78935e38c636R27-R60) …

feat: add gas limit option to raw transactor

---

.changeset/plain-dragons-eat.md
engine/cld/domain/domain.go
engine/cld/domain/domain_test.go

Fixes to correctly reference the difference between dir and file path.

fix: correct function names in domain.go and domain_test.go

---

.changeset/tricky-trams-sin.md
chain/evm/provider/ctf_anvil_provider.go
chain/evm/provider/ctf_anvil_provider_test.go

Because anvil provider can be used outside of testing, the testing.T is not available, however currently , when it is not provided, the code returns nil pointer error during the call to testcontainers.CleanupContainer, this fix handles that scenario and provide a dedicated method for cleaning up container.
```
// Usage in production/non-test contexts with manual cleanup:
//
//	func main() {
//		var once sync.Once
//		config := CTFAnvilChainProviderConfig{
//			Once:           &once,
//			ConfirmFunctor: ConfirmFuncGeth(2 * time.Minute),
//			Port:           "8545", // T not required when Port is provided
//		}
//
//		provider := NewCTFAnvilChainProvider(chainSelector, config)
//		blockchain, err := provider.Initialize(context.Background())
//		if err != nil {
//			log.Fatal(err)
//		}
// …
```

[CLD-518]: fix(anvil): fix nil pointer when T is not provided

---

.changeset/four-grapes-warn.md
engine/cld/domain/domain.go
engine/cld/domain/domain_test.go

This `PR` adds a couple of CI config file paths:
- common.env path (shared defaults)
- environment-specific .env path(s)

feat: adds ci config files path methods

---

.changeset/sweet-frogs-talk.md
engine/cld/environment/names.go
engine/cld/network/network.go
engine/cld/network/network_test.go

Move environment network from cld to cldf.
https://smartcontract-it.atlassian.net/browse/CLD-563

refactor(engine): move env network from cld

---

.changeset/major-walls-stop.md
engine/cld/legacy/cli/cli.go
engine/cld/legacy/cli/cli_test.go
engine/cld/legacy/cli/logger.go
engine/cld/legacy/cli/templates.go
engine/cld/legacy/cli/templates_test.go
go.mod
go.sum
sonar-project.properties

This is a temporary migration to get the CLI package into the CLD engine legacy package.
As we determine how to best design CLI management, we will deprecate this package.

chore: migrate cli package into the CLD engine legacy package

---

offchain/jd/cognito.go
offchain/jd/cognito_test.go

This change inspects the token expiry time each time `Token()` is called on the `CognitoTokenSource` and refreshes the token when it is expired. If the refresh fails, it falls back to full re-authentication.

feat: refresh cognito token when expired

---

.changeset/eleven-turkeys-attack.md
engine/cld/catalog/catalog.go
engine/cld/catalog/catalog_test.go
engine/cld/internal/credentials.go
engine/cld/internal/credentials_test.go
engine/cld/offchain/offchain.go

In order to load environment, we need to load the catalog store first and also the offchain client. These will be used when we load environment.
- added tests
JIRA: https://smartcontract-it.atlassian.net/browse/CLD-586

[CLD-586]: feat(engine): migrate loadCatalogStore & loadOffchainClient

---

engine/cld/legacy/cli/commands/commands.go
engine/cld/legacy/cli/commands/state.go
engine/cld/legacy/cli/commands/state_test.go

This commit migrates the state commands to the cld engine as legacy commands.

chore: migrate state commands to cld engine as legacy

---

.changeset/famous-beans-work.md
deployment/changeset_test.go
deployment/environment.go
deployment/ocr_secrets.go
engine/cld/environment/environment.go
engine/cld/environment/fork.go
offchain/ocr/secrets.go
offchain/ocr/secrets_test.go

This PR moves `ocr_secrets.go` from the `deployment` package to `offchain/ocr`. The original definitions are temporarily preserved as type aliases and will be removed once the transition is fully complete."

chore: moves ocr_secrets.go `deployment` -> `offchain/ocr`

---

.github/workflows/push-main.yml

I noticed in my previous PR, i forgot to download the go module so it can be cached. We need to run go mod download in order to download the go modules for caching.

ci: run go mod download on push

---

.changeset/neat-cases-dig.md
chain/aptos/addrconv.go
chain/aptos/addrconv_test.go
chain/evm/addrconv.go
chain/evm/addrconv_test.go
chain/solana/addrconv.go
chain/solana/addrconv_test.go
chain/sui/addrconv.go
chain/sui/addrconv_test.go
chain/ton/addrconv.go
chain/ton/addrconv_test.go
chain/tron/addrconv.go
chain/tron/addrconv_test.go
chain/utils/addrconv/addrconv.go
chain/utils/addrconv/doc.go
chain/utils/addrconv/registry.go
chain/utils/addrconv/registry_test.go

Context: https://chainlink-core.slack.com/archives/C08QF1BEW4T/p1756934131485399
Design thoughts:
Initially i went with [this design](https://github.com/smartcontractkit/chainlink-deployments-framework/pull/376) where i introduced the AddressToBytes method to the blockchain interface. However i didn quite like this approach because `AddressToBytes` feels out of place in the blockchain interface (it could be its own interface, and to convert address, we dont need the `chain` struct) and this also forces all implementations of blockchain to implement `AddressToBytes`. 
So i went with the approach in this PR, introducing a new interface call AddressConverter and using the strategy pattern for each chain to provide the conversion functionality. This decouples the Address conversion logic from …

[CLD-606]: feat(chain): addr string to bytes conversion

---

chain/evm/provider/ctf_anvil_provider_test.go
chain/tron/provider/ctf_provider_test.go
offchain/jd/provider/ctf_provider_test.go

Some test cases are do not mutate the state of the container, this commit combines those cases in order to reduce the number of containers being created, this will result in quicker test duration and also less memory needed.

test(provider): merge container tests

---

.changeset/petite-feet-obey.md
engine/cld/environment/environment.go

This fixes the issue where the dry run job distributor logic was inverted, but the LoadOffchainClient function was not.
As a temporary fix, we are passing in the inverse of the useDryRunJobDistributor flag to LoadOffchainClient as the `useRealBackends` argument.

fix: fix dry rub job distributor being used by default

---

.changeset/two-ducks-ring.md
engine/cld/environment/environment.go
engine/cld/environment/options.go
engine/cld/environment/options_test.go
engine/cld/legacy/cli/commands/migration_helper.go
engine/cld/legacy/cli/mcmsv2/mcms_v2.go

The environment option OnlyLoadChainsFor [first parameter](https://github.com/smartcontractkit/chainlink-deployments-framework/blob/c2417566058ff4dd502a17d9b28242e26968406a/engine/cld/environment/options.go#L122-L122) is not needed as it is use for logging the migration name which can be removed.
This cleans up the interface as currently users are forced to provide a migration name even when they are not running a migration but just want to load environment eg mcms [here](https://github.com/smartcontractkit/chainlink-deployments-framework/blob/c2417566058ff4dd502a17d9b28242e26968406a/engine/cld/legacy/cli/mcmsv2/mcms_v2.go#L1082-L1082)
NOTE: This is a BREAKING CHANGE, i will perform the upgrade on CLD once this is merged.
**Before:**
```go
environment.OnlyLoadChainsFor("analyze-proposal", …
```

fix(OnlyLoadChainsFor)!: remove migration name parameter for environment option

---

.github/workflows/pull-request-main.yml

In order to reduce tests execution time, i broken the original test step into 2, one for normal tests and the other for provider tests (with docker containers). By running both parallely, tests should finish faster.
Originally the test runs for around 5 minutes, now since we broken it down into 2 , the provider tests take 3 min and the non provider tests take 1 min , so max of both of them is 3.5 min, so we shave off ~1.5-2 minutes through my initial observation.
JIRA: https://smartcontract-it.atlassian.net/browse/CLD-634

[CLD-634]: test: separate unit and provider tests

---

.changeset/lemon-hornets-decide.md
engine/cld/changeset/common.go
engine/cld/legacy/cli/commands/durable-pipelines.go
engine/cld/legacy/cli/commands/template_input.go
engine/cld/legacy/cli/commands/template_input_test.go

Currently for pipelines, when user wants to run a pipeline, they have to create an input yaml file and manually enter the field names and values, if the config required for the changeset is complicated, user have to do some typing and mistakes can happen (eg wrong type, incorrect field name etc) and it gets trickier if config resolver is being used too, this mundane and error prone task can be automated and give our users a better experience.
This commit introduces a new `template-input` command that generates YAML input templates from Go struct types for durable pipeline changesets. The command uses reflection to analyze changeset input types and produces well-formatted YAML templates with type comments to guide users in creating valid input files.
```
go run main.go durable-pipeline …
```

feat: introduce template-input command for generating YAML input

---

.changeset/ninety-doors-move.md
engine/test/runtime/options.go
engine/test/runtime/options_test.go
engine/test/runtime/runtime.go
engine/test/runtime/runtime_test.go

Provides a simpler way to create runtime instances using functional options for environment configuration.

feat: Add `runtime.New()` convenience function for runtime init

---

.changeset/six-comics-camp.md
engine/cld/legacy/cli/commands/durable-pipelines_test.go
engine/cld/legacy/cli/commands/durable_pipeline_yaml.go
engine/cld/legacy/cli/commands/durable_pipeline_yaml_test.go

Raised in the support ticket -https://chainlink-core.slack.com/archives/C08QF1BEW4T/p1758918706928359
**Problem:**
When we execute pipeline, we convert YAML -> JSON -> Code
This is what is happening when there is a really big integer
- YAML parsing converts large numbers like `2000000000000000000000` to `float64(2e+21)`
- JSON marshaling converts `float64(2e+21)` to scientific notation `"2e+21"`
- big.Int cannot unmarshal scientific notation, causing errors
This commit ensure value is converted back to the original format instead of scientific notation.
Long term fix: because of legacy reason, we convert yaml -> json -> code, however we if refactor and remove the middle json, it will make this redundant and cleaner. Something to do in the future.
JIRA: …

[CLD-691]: fix: preserve large integers in YAML to JSON conversion

---

.changeset/every-cars-taste.md
engine/test/environment/environment_test.go
engine/test/environment/options.go
engine/test/onchain/selectors.go
engine/test/onchain/sui.go
engine/test/onchain/sui_test.go
engine/test/onchain/tron.go
engine/test/onchain/tron_test.go

This adds the ability to load Sui and Tron chains as containerized chains in the test engine.

feat: adds support for Sui and Tron chains to the test engine

---

.changeset/full-doors-peel.md
operations/operation.go
operations/operation_test.go

This addresses the issue where YAML-unmarshaled inputs (map[string]any) 
would fail type assertion in AsUntyped operations when unmarshaled from YAML file. Users can now explicitly 
opt-in to marshaling conversion when needed with `AsUntypedRelaxed`
The `AsUntyped()` method was failing with "input type mismatch" errors when inputs came from YAML unmarshaling, even when the data was structurally compatible with the expected input type.
When unmarshaling YAML in Go, the result is typically `map[string]interface{}` for objects, even if the original data came from a well-defined struct. The original `AsUntyped()` implementation used strict type assertion:
```go
if typedInput, ok = input.(IN); !ok {
return nil, errors.New("input type mismatch")
}
```
This would fail because …

feat(operations): introduce AsUntypedRelaxed

---

datastore/catalog/remote/grpc.go
go.mod
go.sum

- Update github.com/smartcontractkit/chainlink-protos/op-catalog from v0.0.1 to v0.0.3
- DeploymentsDatastoreClient -> DatastoreClient
- NewDeploymentsDatastoreClient -> NewDatastoreClient

chore: update op-catalog to v0.0.3

---

.changeset/great-wasps-lie.md
datastore/catalog/memory/address_ref_store.go
datastore/catalog/memory/chain_metadata_store.go
datastore/catalog/memory/contract_metadata_store.go
datastore/catalog/memory/datastore.go
datastore/catalog/memory/db_controller.go
datastore/catalog/memory/db_controller_test.go
datastore/catalog/memory/env_metadata_store.go

Previously we have to use context.TODO, we should pass it in the context from the upstream instead.
JIRA: https://smartcontract-it.atlassian.net/browse/CLD-715

[CLD-715]: fix(catalog/memory): update db controller to accept context

---

.changeset/nasty-taxes-kick.md
datastore/catalog/memory/address_ref_store.go
datastore/catalog/memory/address_ref_store_test.go
datastore/catalog/memory/chain_metadata_store.go
datastore/catalog/memory/chain_metadata_store_test.go
datastore/catalog/memory/contract_metadata_store.go
datastore/catalog/memory/contract_metadata_store_test.go
datastore/catalog/memory/datastore.go
datastore/catalog/memory/datstore_test.go
datastore/catalog/memory/env_metadata_store.go
datastore/catalog/memory/env_metadata_store_test.go

The MemoryDataStoreConfig is not used. We can remove it.
JIRA: https://smartcontract-it.atlassian.net/browse/CLD-719

[CLD-719]: fix(catalog/memory): remove unused config
