.github/dependabot.yml
package.json
pnpm-lock.yaml

We will use dependabot to manage package updates

ci: add dependabot

---

.changeset/stale-doodles-smoke.md
deployment/changeset.go
deployment/changeset_test.go
go.mod
go.sum

Lift and shift, migration of the changeset and changeset output.
https://smartcontract-it.atlassian.net/browse/CLD-152

feat(changeset):migrate changeset and changeset output from core

---

.changeset/honest-clouds-think.md
deployment/aptos_chain.go
deployment/environment.go

Newest changes from chainlink for aptos. 
https://smartcontract-it.atlassian.net/browse/CLD-148

chore(aptos):lift and shift from chainlink updates

---

.changeset/ten-animals-tickle.md
deployment/helpers.go

These are helper functions are that useful when writing changesets. Missed one from previous PR
JIRA: https://smartcontract-it.atlassian.net/browse/CLD-212

[CLD-212]: fix(deployment): migrate missed helper

---

README.md

Include a new import section and address the incorrect usage section

docs(readme): update usage section

---

.github/workflows/pull-request-main.yml
sonar-project.properties

This pull request introduces SonarQube integration to enhance code quality analysis and reporting. The changes include adding a SonarQube job to the CI workflow and configuring the SonarQube project properties for the repository.
* [`.github/workflows/pull-request-main.yml`](diffhunk://#diff-deba6b8d69fe72e6186b64f7934e93aa1d8213648ef0e99400caa36df42883f0R46-R57): Added a new `sonarqube` job to perform SonarQube scans during pull requests. This job runs after the `ci-test`, `ci-lint-misc`, and `ci-lint` jobs and uses a custom GitHub action for the scan.
* [`sonar-project.properties`](diffhunk://#diff-43ed9d31bea2a6d518d69836bcd1a8e6bd81bf4df96c4745792c220ca5aa549cR1-R26): Added a configuration file for SonarQube, specifying project metadata, source directories, exclusions for static …

introduce sonarqube

---

chain/aptos/aptos_chain_test.go
chain/evm/evm_chain_test.go
chain/solana/solana_chain_test.go
chain/sui/sui_chain_test.go

Testing for the chain info for all the chains.

test: add chain tests

---

.changeset/forty-lizards-mate.md
chain/blockchain.go
chain/blockchain_test.go

- Introduce All method for blockchain which returns all blockchains
- New constructor for BlockChains to create from slice

feat: New AllChains() and new constructor for BlockChain

---

.github/workflows/pull-request-main.yml
.github/workflows/schedule-main.yml
.tool-versions

Upgrades the linter and the action.
Upgrading the action solves the cache issue

upgrade linter to v2.1.6

---

.changeset/shy-peas-occur.md
deployment/environment.go

We should be using NewEnvironment going forward
JIRA: https://smartcontract-it.atlassian.net/browse/CLD-281

[CLD-281]: fix: remove NewCLDFEnvironment

---

README.md

Some instructions to get started on adding a new chain.
JIRA: https://smartcontract-it.atlassian.net/browse/CLD-322

[CLD-322]: docs(readme): add how to add a new chain

---

.github/workflows/pull-request-main.yml

Adds sonar token check if its not unset or empty to verify dependabot got access to the secret.

add sonar token check, to help debug sonar dependabot issue

---

.changeset/shy-emus-create.md
chain/evm/evm_chain.go
chain/evm/provider/confirm_functor.go
chain/evm/provider/confirm_functor_test.go
chain/evm/provider/fake_test.go
chain/evm/provider/rpc_provider.go
chain/evm/provider/rpc_provider_test.go
chain/evm/provider/seth_client.go
chain/evm/provider/seth_client_test.go
chain/evm/provider/seth_test.go
chain/evm/provider/sim_provider_test.go
chain/evm/provider/transactor_generator.go
chain/evm/provider/transactor_generator_test.go
chain/evm/provider/zksync_ctf_provider_test.go
go.mod
go.sum

This adds a simple EVM RPC provider that can be used to interact with Ethereum-like chains. It supports loading a private key from raw, with KMS integration planned for the future.

feat: Adds an EVM RPC Provider

---

chain/evm/provider/kms_signer.go
chain/evm/provider/kms_signer_test.go

This adds a new method `SignHash` to the KMS Client interface, allowing signing of arbitrary hashes. This is useful for scenarios where the signing operation does not require a full transaction context, such as for signing zkSync messages.
The existing `GetTransactOpts` method has been updated to use the new `SignHash` method for code resuability.

feature: add a SignHash method to the KMS Client

---

datastore/catalog/address_ref_store_test.go
datastore/catalog/chain_metadata_store_test.go
datastore/catalog/contract_metadata_store_test.go
datastore/catalog/env_metadata_store_test.go

Small one to tweak catalog datastore test setup timeouts

chore(catalog): bump test setup timeouts

---

chain/doc.go
offchain/doc.go

Introduce package level godoc for chain and offchain explaining the framework and interfaces to implement.
These docs will be available to be viewed at https://pkg.go.dev/github.com/smartcontractkit/chainlink-deployments-framework

docs: godoc for chain and offchain

---

.changeset/wet-days-raise.md
engine/cld/lib/fileutils/fileutils.go
engine/cld/lib/fileutils/fileutils_test.go
engine/cld/lib/jsonutils/jsonutils.go
engine/cld/lib/jsonutils/jsonutils_test.go
engine/cld/nodes/nodes.go
engine/cld/nodes/nodes_test.go

migrate json file utils from cld -> cldf

migrate(file-json-utils): from cldf to cld

---

.changeset/chubby-boats-kiss.md
engine/cld/config/env/config.go

Add Sui env config

---

.changeset/ripe-loops-own.md
chain/sui/signer.go
chain/sui/signer_test.go

Encodes message payload as base64 before signing

Fix Sui signer

---

.changeset/dull-cloths-agree.md
engine/cld/legacy/cli/commands/env.go
engine/cld/legacy/cli/commands/env_test.go

Migrate env cli commands from CLD
JIRA: https://smartcontract-it.atlassian.net/browse/CLD-528

[CLD-528]: feat(command): migrate env command

---

engine/cld/environment/names.go

Add comment to not delete the file.

chore(engine): add note not to delete environment names constant file

---

README.md
engine/cld/chains/doc.go

Updating the section on how to add new chain to contain the latest info.
Also added doc.go for engine/cld/chains, these are the places external users will likely to contribute when adding a new chain.
JIRA: https://smartcontract-it.atlassian.net/browse/CLD-592

[CLD-592]: docs: update readme

---

.github/CODEOWNERS
engine/cld/legacy/cli/mcmsv2/err_decode_helpers.go
engine/cld/legacy/cli/mcmsv2/err_decode_helpers_test.go
engine/cld/legacy/cli/mcmsv2/helpers.go
engine/cld/legacy/cli/mcmsv2/layout/layout_mutations.go
engine/cld/legacy/cli/mcmsv2/layout/mcms_layout.json
engine/cld/legacy/cli/mcmsv2/mcms_v2.go
engine/cld/legacy/cli/mcmsv2/mcms_v2_test.go
engine/cld/legacy/cli/mcmsv2/testdata/proposal.json
go.mod
go.sum

Ports MCMSv2 CLI from CLD to CLDF.

feat: port mcmsv2 cli commands [DX-1733]

---

.changeset/sixty-ears-train.md
engine/cld/legacy/cli/mcmsv2/helpers.go
engine/cld/legacy/cli/mcmsv2/mcms_v2.go
go.mod
go.sum

Add Sui MCMS support

---

.github/workflows/pull-request-main.yml
.github/workflows/push-main.yml
.github/workflows/schedule-main.yml

Fixing sec findings https://github.com/smartcontractkit/chainlink-deployments-framework/security/code-scanning

CLD-684: Fix workflow permissions

---

engine/test/runtime/doc.go

Updates the test engine docs to include the new API changes for setting up the environment and runtime. Also add information on the MCMS related tasks and usage patterns.

chore: improve test engine docs

---

.changeset/new-wolves-follow.md
engine/cld/environment/anvil.go
engine/cld/environment/fork.go

Otherwise, fork tests on domains that don't use the address book will always fail as no chains are ever loaded.

fix: anvil env should check for addresses from DataStore too
